// src/cli/banner.ts — GENERATED by `bun run generate:banner`. Do NOT edit by hand.
// Source: figlet -f "ANSI Shadow" "Verb" + figlet -f "ANSI Shadow" "um"
//
// Exported as per-line arrays so the welcome screen can render each row as its
// own <text> with two adjacent <span>s. Multi-line strings inside a single
// <span> would force a newline between the dim and accent halves, stacking
// "um" below "Verb" instead of placing them side-by-side.
export const BANNER_DIM_LINES: readonly string[] = [
  "██╗   ██╗███████╗██████╗ ██████╗ ",
  "██║   ██║██╔════╝██╔══██╗██╔══██╗",
  "██║   ██║█████╗  ██████╔╝██████╔╝",
  "╚██╗ ██╔╝██╔══╝  ██╔══██╗██╔══██╗",
  " ╚████╔╝ ███████╗██║  ██║██████╔╝",
  "  ╚═══╝  ╚══════╝╚═╝  ╚═╝╚═════╝ ",
  "                                 ",
];
export const BANNER_ACCENT_LINES: readonly string[] = [
  "██╗   ██╗███╗   ███╗",
  "██║   ██║████╗ ████║",
  "██║   ██║██╔████╔██║",
  "██║   ██║██║╚██╔╝██║",
  "╚██████╔╝██║ ╚═╝ ██║",
  " ╚═════╝ ╚═╝     ╚═╝",
  "                    ",
];
export const BANNER_WIDTH = 53;
