// Why: the daily verse pool lives in the CLI layer because it is configuration
// data, not a domain concept (the proposal explicitly rejected a VersePool port).
// Each entry is a USFM string + chapter + verse; the pool size is 365 (I1) so
// no verse repeats within a year. Curation style: devotional / comfort canon
// — Psalms-heavy with cornerstone NT verses (John 3:16, Rom 8:28, Phil 4:6-7,
// Jer 29:11, Pro 3:5-6, Isa 40:31, etc.). Light on genealogies, Levitical law,
// prophetic oracles, judgment passages.
//
// Maintenance: any edit MUST keep length === 365. The "every entry has a valid
// USFM" test in src/application/verse-pool.test.ts catches typos at `bun test`
// time. To rebalance, edit entries in place — the picker is size-agnostic but
// the test fails if length drifts from 365.

import type { PoolEntry } from "@/application/verse-pool";

export const VERSE_POOL: readonly PoolEntry[] = [
  // Index 0 — the wrap-around entry (Dec 31 non-leap wraps here)
  { usfm: "JHN", chapter: 3, verse: 16 },

  // === Psalms (80 entries, indices 1–80) — devotional anchors ===
  { usfm: "PSA", chapter: 1, verse: 1 },
  { usfm: "PSA", chapter: 1, verse: 3 },
  { usfm: "PSA", chapter: 4, verse: 8 },
  { usfm: "PSA", chapter: 5, verse: 3 },
  { usfm: "PSA", chapter: 8, verse: 3 },
  { usfm: "PSA", chapter: 8, verse: 4 },
  { usfm: "PSA", chapter: 9, verse: 9 },
  { usfm: "PSA", chapter: 9, verse: 10 },
  { usfm: "PSA", chapter: 16, verse: 8 },
  { usfm: "PSA", chapter: 16, verse: 11 },
  { usfm: "PSA", chapter: 18, verse: 2 },
  { usfm: "PSA", chapter: 19, verse: 1 },
  { usfm: "PSA", chapter: 19, verse: 14 },
  { usfm: "PSA", chapter: 20, verse: 7 },
  { usfm: "PSA", chapter: 23, verse: 1 },
  { usfm: "PSA", chapter: 23, verse: 4 },
  { usfm: "PSA", chapter: 23, verse: 6 },
  { usfm: "PSA", chapter: 25, verse: 4 },
  { usfm: "PSA", chapter: 25, verse: 5 },
  { usfm: "PSA", chapter: 27, verse: 1 },
  { usfm: "PSA", chapter: 27, verse: 4 },
  { usfm: "PSA", chapter: 27, verse: 14 },
  { usfm: "PSA", chapter: 28, verse: 7 },
  { usfm: "PSA", chapter: 29, verse: 11 },
  { usfm: "PSA", chapter: 30, verse: 5 },
  { usfm: "PSA", chapter: 31, verse: 24 },
  { usfm: "PSA", chapter: 32, verse: 8 },
  { usfm: "PSA", chapter: 33, verse: 4 },
  { usfm: "PSA", chapter: 33, verse: 22 },
  { usfm: "PSA", chapter: 34, verse: 4 },
  { usfm: "PSA", chapter: 34, verse: 8 },
  { usfm: "PSA", chapter: 34, verse: 18 },
  { usfm: "PSA", chapter: 36, verse: 5 },
  { usfm: "PSA", chapter: 37, verse: 4 },
  { usfm: "PSA", chapter: 37, verse: 5 },
  { usfm: "PSA", chapter: 37, verse: 7 },
  { usfm: "PSA", chapter: 37, verse: 23 },
  { usfm: "PSA", chapter: 40, verse: 1 },
  { usfm: "PSA", chapter: 42, verse: 1 },
  { usfm: "PSA", chapter: 42, verse: 11 },
  { usfm: "PSA", chapter: 46, verse: 1 },
  { usfm: "PSA", chapter: 46, verse: 10 },
  { usfm: "PSA", chapter: 51, verse: 10 },
  { usfm: "PSA", chapter: 51, verse: 12 },
  { usfm: "PSA", chapter: 55, verse: 22 },
  { usfm: "PSA", chapter: 56, verse: 3 },
  { usfm: "PSA", chapter: 62, verse: 1 },
  { usfm: "PSA", chapter: 62, verse: 8 },
  { usfm: "PSA", chapter: 63, verse: 1 },
  { usfm: "PSA", chapter: 63, verse: 3 },
  { usfm: "PSA", chapter: 66, verse: 19 },
  { usfm: "PSA", chapter: 71, verse: 5 },
  { usfm: "PSA", chapter: 73, verse: 26 },
  { usfm: "PSA", chapter: 84, verse: 10 },
  { usfm: "PSA", chapter: 86, verse: 5 },
  { usfm: "PSA", chapter: 86, verse: 15 },
  { usfm: "PSA", chapter: 90, verse: 12 },
  { usfm: "PSA", chapter: 91, verse: 1 },
  { usfm: "PSA", chapter: 91, verse: 2 },
  { usfm: "PSA", chapter: 91, verse: 11 },
  { usfm: "PSA", chapter: 94, verse: 19 },
  { usfm: "PSA", chapter: 100, verse: 3 },
  { usfm: "PSA", chapter: 100, verse: 5 },
  { usfm: "PSA", chapter: 103, verse: 2 },
  { usfm: "PSA", chapter: 103, verse: 8 },
  { usfm: "PSA", chapter: 103, verse: 12 },
  { usfm: "PSA", chapter: 107, verse: 1 },
  { usfm: "PSA", chapter: 116, verse: 1 },
  { usfm: "PSA", chapter: 118, verse: 24 },
  { usfm: "PSA", chapter: 119, verse: 11 },
  { usfm: "PSA", chapter: 119, verse: 105 },
  { usfm: "PSA", chapter: 121, verse: 1 },
  { usfm: "PSA", chapter: 121, verse: 2 },
  { usfm: "PSA", chapter: 121, verse: 8 },
  { usfm: "PSA", chapter: 126, verse: 5 },
  { usfm: "PSA", chapter: 130, verse: 5 },
  { usfm: "PSA", chapter: 138, verse: 8 },
  { usfm: "PSA", chapter: 139, verse: 14 },
  { usfm: "PSA", chapter: 139, verse: 23 },
  { usfm: "PSA", chapter: 143, verse: 8 },

  // === Proverbs (50 entries, indices 80–129) — wisdom ===
  { usfm: "PRO", chapter: 1, verse: 7 },
  { usfm: "PRO", chapter: 2, verse: 6 },
  { usfm: "PRO", chapter: 3, verse: 3 },
  { usfm: "PRO", chapter: 3, verse: 5 },
  { usfm: "PRO", chapter: 3, verse: 6 },
  { usfm: "PRO", chapter: 3, verse: 9 },
  { usfm: "PRO", chapter: 3, verse: 12 },
  { usfm: "PRO", chapter: 3, verse: 27 },
  { usfm: "PRO", chapter: 4, verse: 7 },
  { usfm: "PRO", chapter: 4, verse: 23 },
  { usfm: "PRO", chapter: 4, verse: 25 },
  { usfm: "PRO", chapter: 8, verse: 11 },
  { usfm: "PRO", chapter: 9, verse: 10 },
  { usfm: "PRO", chapter: 10, verse: 9 },
  { usfm: "PRO", chapter: 10, verse: 12 },
  { usfm: "PRO", chapter: 11, verse: 2 },
  { usfm: "PRO", chapter: 11, verse: 25 },
  { usfm: "PRO", chapter: 12, verse: 18 },
  { usfm: "PRO", chapter: 12, verse: 25 },
  { usfm: "PRO", chapter: 13, verse: 20 },
  { usfm: "PRO", chapter: 14, verse: 26 },
  { usfm: "PRO", chapter: 14, verse: 29 },
  { usfm: "PRO", chapter: 15, verse: 1 },
  { usfm: "PRO", chapter: 15, verse: 13 },
  { usfm: "PRO", chapter: 15, verse: 22 },
  { usfm: "PRO", chapter: 16, verse: 3 },
  { usfm: "PRO", chapter: 16, verse: 7 },
  { usfm: "PRO", chapter: 16, verse: 9 },
  { usfm: "PRO", chapter: 16, verse: 24 },
  { usfm: "PRO", chapter: 17, verse: 17 },
  { usfm: "PRO", chapter: 17, verse: 22 },
  { usfm: "PRO", chapter: 18, verse: 10 },
  { usfm: "PRO", chapter: 18, verse: 24 },
  { usfm: "PRO", chapter: 19, verse: 11 },
  { usfm: "PRO", chapter: 19, verse: 17 },
  { usfm: "PRO", chapter: 19, verse: 21 },
  { usfm: "PRO", chapter: 20, verse: 7 },
  { usfm: "PRO", chapter: 21, verse: 21 },
  { usfm: "PRO", chapter: 22, verse: 1 },
  { usfm: "PRO", chapter: 22, verse: 6 },
  { usfm: "PRO", chapter: 22, verse: 9 },
  { usfm: "PRO", chapter: 23, verse: 18 },
  { usfm: "PRO", chapter: 24, verse: 16 },
  { usfm: "PRO", chapter: 25, verse: 11 },
  { usfm: "PRO", chapter: 27, verse: 17 },
  { usfm: "PRO", chapter: 28, verse: 13 },
  { usfm: "PRO", chapter: 29, verse: 25 },
  { usfm: "PRO", chapter: 30, verse: 5 },
  { usfm: "PRO", chapter: 31, verse: 25 },
  { usfm: "PRO", chapter: 31, verse: 30 },

  // === John (40 entries, indices 131–170) — gospel cornerstones ===
  { usfm: "JHN", chapter: 1, verse: 1 },
  { usfm: "JHN", chapter: 1, verse: 4 },
  { usfm: "JHN", chapter: 1, verse: 5 },
  { usfm: "JHN", chapter: 1, verse: 12 },
  { usfm: "JHN", chapter: 1, verse: 14 },
  { usfm: "JHN", chapter: 1, verse: 16 },
  { usfm: "JHN", chapter: 1, verse: 29 },
  { usfm: "JHN", chapter: 3, verse: 17 },
  { usfm: "JHN", chapter: 3, verse: 30 },
  { usfm: "JHN", chapter: 4, verse: 14 },
  { usfm: "JHN", chapter: 4, verse: 24 },
  { usfm: "JHN", chapter: 6, verse: 35 },
  { usfm: "JHN", chapter: 6, verse: 37 },
  { usfm: "JHN", chapter: 6, verse: 47 },
  { usfm: "JHN", chapter: 7, verse: 38 },
  { usfm: "JHN", chapter: 8, verse: 12 },
  { usfm: "JHN", chapter: 8, verse: 31 },
  { usfm: "JHN", chapter: 8, verse: 32 },
  { usfm: "JHN", chapter: 8, verse: 36 },
  { usfm: "JHN", chapter: 10, verse: 10 },
  { usfm: "JHN", chapter: 10, verse: 11 },
  { usfm: "JHN", chapter: 10, verse: 27 },
  { usfm: "JHN", chapter: 10, verse: 28 },
  { usfm: "JHN", chapter: 11, verse: 25 },
  { usfm: "JHN", chapter: 13, verse: 34 },
  { usfm: "JHN", chapter: 13, verse: 35 },
  { usfm: "JHN", chapter: 14, verse: 1 },
  { usfm: "JHN", chapter: 14, verse: 2 },
  { usfm: "JHN", chapter: 14, verse: 6 },
  { usfm: "JHN", chapter: 14, verse: 15 },
  { usfm: "JHN", chapter: 14, verse: 21 },
  { usfm: "JHN", chapter: 14, verse: 27 },
  { usfm: "JHN", chapter: 15, verse: 4 },
  { usfm: "JHN", chapter: 15, verse: 5 },
  { usfm: "JHN", chapter: 15, verse: 7 },
  { usfm: "JHN", chapter: 15, verse: 13 },
  { usfm: "JHN", chapter: 16, verse: 33 },
  { usfm: "JHN", chapter: 17, verse: 3 },
  { usfm: "JHN", chapter: 20, verse: 29 },
  { usfm: "JHN", chapter: 21, verse: 17 },

  // === Romans (35 entries, indices 171–205) ===
  { usfm: "ROM", chapter: 1, verse: 16 },
  { usfm: "ROM", chapter: 1, verse: 17 },
  { usfm: "ROM", chapter: 3, verse: 23 },
  { usfm: "ROM", chapter: 3, verse: 24 },
  { usfm: "ROM", chapter: 5, verse: 1 },
  { usfm: "ROM", chapter: 5, verse: 3 },
  { usfm: "ROM", chapter: 5, verse: 5 },
  { usfm: "ROM", chapter: 5, verse: 8 },
  { usfm: "ROM", chapter: 6, verse: 23 },
  { usfm: "ROM", chapter: 8, verse: 1 },
  { usfm: "ROM", chapter: 8, verse: 6 },
  { usfm: "ROM", chapter: 8, verse: 11 },
  { usfm: "ROM", chapter: 8, verse: 14 },
  { usfm: "ROM", chapter: 8, verse: 15 },
  { usfm: "ROM", chapter: 8, verse: 16 },
  { usfm: "ROM", chapter: 8, verse: 17 },
  { usfm: "ROM", chapter: 8, verse: 18 },
  { usfm: "ROM", chapter: 8, verse: 26 },
  { usfm: "ROM", chapter: 8, verse: 28 },
  { usfm: "ROM", chapter: 8, verse: 31 },
  { usfm: "ROM", chapter: 8, verse: 35 },
  { usfm: "ROM", chapter: 8, verse: 37 },
  { usfm: "ROM", chapter: 8, verse: 38 },
  { usfm: "ROM", chapter: 8, verse: 39 },
  { usfm: "ROM", chapter: 10, verse: 9 },
  { usfm: "ROM", chapter: 10, verse: 13 },
  { usfm: "ROM", chapter: 10, verse: 17 },
  { usfm: "ROM", chapter: 12, verse: 1 },
  { usfm: "ROM", chapter: 12, verse: 2 },
  { usfm: "ROM", chapter: 12, verse: 9 },
  { usfm: "ROM", chapter: 12, verse: 10 },
  { usfm: "ROM", chapter: 12, verse: 12 },
  { usfm: "ROM", chapter: 12, verse: 18 },
  { usfm: "ROM", chapter: 14, verse: 8 },
  { usfm: "ROM", chapter: 15, verse: 13 },

  // === Philippians (25 entries, indices 206–230) ===
  { usfm: "PHP", chapter: 1, verse: 6 },
  { usfm: "PHP", chapter: 1, verse: 9 },
  { usfm: "PHP", chapter: 1, verse: 21 },
  { usfm: "PHP", chapter: 1, verse: 27 },
  { usfm: "PHP", chapter: 2, verse: 3 },
  { usfm: "PHP", chapter: 2, verse: 4 },
  { usfm: "PHP", chapter: 2, verse: 5 },
  { usfm: "PHP", chapter: 2, verse: 13 },
  { usfm: "PHP", chapter: 2, verse: 14 },
  { usfm: "PHP", chapter: 3, verse: 8 },
  { usfm: "PHP", chapter: 3, verse: 13 },
  { usfm: "PHP", chapter: 3, verse: 14 },
  { usfm: "PHP", chapter: 3, verse: 20 },
  { usfm: "PHP", chapter: 4, verse: 4 },
  { usfm: "PHP", chapter: 4, verse: 5 },
  { usfm: "PHP", chapter: 4, verse: 6 },
  { usfm: "PHP", chapter: 4, verse: 7 },
  { usfm: "PHP", chapter: 4, verse: 8 },
  { usfm: "PHP", chapter: 4, verse: 9 },
  { usfm: "PHP", chapter: 4, verse: 11 },
  { usfm: "PHP", chapter: 4, verse: 12 },
  { usfm: "PHP", chapter: 4, verse: 13 },
  { usfm: "PHP", chapter: 4, verse: 19 },
  { usfm: "PHP", chapter: 1, verse: 3 },
  { usfm: "PHP", chapter: 2, verse: 11 },

  // === Isaiah (20 entries, indices 231–250) — comfort and promise ===
  { usfm: "ISA", chapter: 9, verse: 6 },
  { usfm: "ISA", chapter: 12, verse: 2 },
  { usfm: "ISA", chapter: 26, verse: 3 },
  { usfm: "ISA", chapter: 26, verse: 4 },
  { usfm: "ISA", chapter: 30, verse: 15 },
  { usfm: "ISA", chapter: 30, verse: 21 },
  { usfm: "ISA", chapter: 40, verse: 8 },
  { usfm: "ISA", chapter: 40, verse: 28 },
  { usfm: "ISA", chapter: 40, verse: 29 },
  { usfm: "ISA", chapter: 40, verse: 31 },
  { usfm: "ISA", chapter: 41, verse: 10 },
  { usfm: "ISA", chapter: 41, verse: 13 },
  { usfm: "ISA", chapter: 43, verse: 1 },
  { usfm: "ISA", chapter: 43, verse: 2 },
  { usfm: "ISA", chapter: 43, verse: 18 },
  { usfm: "ISA", chapter: 43, verse: 19 },
  { usfm: "ISA", chapter: 53, verse: 5 },
  { usfm: "ISA", chapter: 53, verse: 6 },
  { usfm: "ISA", chapter: 55, verse: 8 },
  { usfm: "ISA", chapter: 55, verse: 11 },

  // === Matthew (15 entries, indices 251–265) ===
  { usfm: "MAT", chapter: 5, verse: 3 },
  { usfm: "MAT", chapter: 5, verse: 4 },
  { usfm: "MAT", chapter: 5, verse: 6 },
  { usfm: "MAT", chapter: 5, verse: 8 },
  { usfm: "MAT", chapter: 5, verse: 9 },
  { usfm: "MAT", chapter: 5, verse: 14 },
  { usfm: "MAT", chapter: 5, verse: 16 },
  { usfm: "MAT", chapter: 5, verse: 44 },
  { usfm: "MAT", chapter: 6, verse: 21 },
  { usfm: "MAT", chapter: 6, verse: 33 },
  { usfm: "MAT", chapter: 6, verse: 34 },
  { usfm: "MAT", chapter: 7, verse: 7 },
  { usfm: "MAT", chapter: 11, verse: 28 },
  { usfm: "MAT", chapter: 11, verse: 29 },
  { usfm: "MAT", chapter: 28, verse: 19 },

  // === 1 John (8 entries, indices 266–273) ===
  { usfm: "1JN", chapter: 1, verse: 7 },
  { usfm: "1JN", chapter: 1, verse: 9 },
  { usfm: "1JN", chapter: 3, verse: 1 },
  { usfm: "1JN", chapter: 3, verse: 16 },
  { usfm: "1JN", chapter: 3, verse: 18 },
  { usfm: "1JN", chapter: 4, verse: 7 },
  { usfm: "1JN", chapter: 4, verse: 18 },
  { usfm: "1JN", chapter: 4, verse: 19 },

  // === James (7 entries, indices 274–280) ===
  { usfm: "JAS", chapter: 1, verse: 2 },
  { usfm: "JAS", chapter: 1, verse: 5 },
  { usfm: "JAS", chapter: 1, verse: 12 },
  { usfm: "JAS", chapter: 1, verse: 17 },
  { usfm: "JAS", chapter: 1, verse: 19 },
  { usfm: "JAS", chapter: 1, verse: 22 },
  { usfm: "JAS", chapter: 4, verse: 7 },

  // === Hebrews (10 entries, indices 281–290) ===
  { usfm: "HEB", chapter: 4, verse: 12 },
  { usfm: "HEB", chapter: 4, verse: 16 },
  { usfm: "HEB", chapter: 6, verse: 19 },
  { usfm: "HEB", chapter: 10, verse: 23 },
  { usfm: "HEB", chapter: 10, verse: 24 },
  { usfm: "HEB", chapter: 11, verse: 1 },
  { usfm: "HEB", chapter: 11, verse: 6 },
  { usfm: "HEB", chapter: 12, verse: 1 },
  { usfm: "HEB", chapter: 12, verse: 2 },
  { usfm: "HEB", chapter: 13, verse: 5 },

  // === Ephesians (12 entries, indices 291–302) ===
  { usfm: "EPH", chapter: 1, verse: 7 },
  { usfm: "EPH", chapter: 2, verse: 4 },
  { usfm: "EPH", chapter: 2, verse: 8 },
  { usfm: "EPH", chapter: 2, verse: 10 },
  { usfm: "EPH", chapter: 3, verse: 16 },
  { usfm: "EPH", chapter: 3, verse: 20 },
  { usfm: "EPH", chapter: 4, verse: 2 },
  { usfm: "EPH", chapter: 4, verse: 29 },
  { usfm: "EPH", chapter: 4, verse: 32 },
  { usfm: "EPH", chapter: 5, verse: 1 },
  { usfm: "EPH", chapter: 6, verse: 10 },
  { usfm: "EPH", chapter: 6, verse: 11 },

  // === Luke (10 entries, indices 303–312) ===
  { usfm: "LUK", chapter: 1, verse: 37 },
  { usfm: "LUK", chapter: 6, verse: 31 },
  { usfm: "LUK", chapter: 6, verse: 35 },
  { usfm: "LUK", chapter: 6, verse: 38 },
  { usfm: "LUK", chapter: 9, verse: 23 },
  { usfm: "LUK", chapter: 10, verse: 27 },
  { usfm: "LUK", chapter: 11, verse: 9 },
  { usfm: "LUK", chapter: 12, verse: 7 },
  { usfm: "LUK", chapter: 12, verse: 32 },
  { usfm: "LUK", chapter: 18, verse: 27 },

  // === 1 Peter (8 entries, indices 313–320) ===
  { usfm: "1PE", chapter: 1, verse: 3 },
  { usfm: "1PE", chapter: 1, verse: 7 },
  { usfm: "1PE", chapter: 2, verse: 9 },
  { usfm: "1PE", chapter: 3, verse: 8 },
  { usfm: "1PE", chapter: 4, verse: 8 },
  { usfm: "1PE", chapter: 4, verse: 10 },
  { usfm: "1PE", chapter: 5, verse: 6 },
  { usfm: "1PE", chapter: 5, verse: 7 },

  // === Colossians (6 entries, indices 321–326) ===
  { usfm: "COL", chapter: 3, verse: 2 },
  { usfm: "COL", chapter: 3, verse: 12 },
  { usfm: "COL", chapter: 3, verse: 13 },
  { usfm: "COL", chapter: 3, verse: 15 },
  { usfm: "COL", chapter: 3, verse: 17 },
  { usfm: "COL", chapter: 3, verse: 23 },

  // === Galatians (5 entries, indices 327–331) ===
  { usfm: "GAL", chapter: 2, verse: 20 },
  { usfm: "GAL", chapter: 5, verse: 13 },
  { usfm: "GAL", chapter: 5, verse: 22 },
  { usfm: "GAL", chapter: 5, verse: 23 },
  { usfm: "GAL", chapter: 6, verse: 9 },

  // === Genesis (5 entries, indices 332–336) ===
  { usfm: "GEN", chapter: 1, verse: 1 },
  { usfm: "GEN", chapter: 1, verse: 27 },
  { usfm: "GEN", chapter: 1, verse: 31 },
  { usfm: "GEN", chapter: 28, verse: 15 },
  { usfm: "GEN", chapter: 50, verse: 20 },

  // === Deuteronomy (5 entries, indices 337–341) ===
  { usfm: "DEU", chapter: 6, verse: 5 },
  { usfm: "DEU", chapter: 6, verse: 6 },
  { usfm: "DEU", chapter: 31, verse: 6 },
  { usfm: "DEU", chapter: 31, verse: 8 },
  { usfm: "DEU", chapter: 33, verse: 27 },

  // === Mark (5 entries, indices 342–346) ===
  { usfm: "MRK", chapter: 9, verse: 23 },
  { usfm: "MRK", chapter: 10, verse: 27 },
  { usfm: "MRK", chapter: 10, verse: 45 },
  { usfm: "MRK", chapter: 11, verse: 24 },
  { usfm: "MRK", chapter: 12, verse: 30 },

  // === 2 Timothy (4 entries, indices 347–350) ===
  { usfm: "2TI", chapter: 1, verse: 7 },
  { usfm: "2TI", chapter: 2, verse: 13 },
  { usfm: "2TI", chapter: 2, verse: 15 },
  { usfm: "2TI", chapter: 3, verse: 16 },

  // === Acts (4 entries, indices 351–354) ===
  { usfm: "ACT", chapter: 1, verse: 8 },
  { usfm: "ACT", chapter: 2, verse: 38 },
  { usfm: "ACT", chapter: 4, verse: 12 },
  { usfm: "ACT", chapter: 20, verse: 35 },

  // === Joshua (3 entries, indices 355–357) ===
  { usfm: "JOS", chapter: 1, verse: 8 },
  { usfm: "JOS", chapter: 1, verse: 9 },
  { usfm: "JOS", chapter: 24, verse: 15 },

  // === 1 Thessalonians (3 entries, indices 358–360) ===
  { usfm: "1TH", chapter: 5, verse: 11 },
  { usfm: "1TH", chapter: 5, verse: 16 },
  { usfm: "1TH", chapter: 5, verse: 17 },

  // === Jeremiah (3 entries, indices 361–363) ===
  { usfm: "JER", chapter: 17, verse: 7 },
  { usfm: "JER", chapter: 29, verse: 11 },
  { usfm: "JER", chapter: 33, verse: 3 },

  // === Lamentations (1 entry, index 364) — STOP HERE, length === 365 ===
  { usfm: "LAM", chapter: 3, verse: 22 },
];
