// scripts/generate-banner.ts — dev tooling. Generates src/cli/banner.ts.
// Run via: bun run generate:banner
// figlet is a devDependency — it is NEVER imported by application code at runtime.

import figlet from "figlet";
import { join } from "path";

const projectRoot = join(import.meta.dir, "..");
const outputPath = join(projectRoot, "src", "cli", "banner.ts");

const art = figlet.textSync("Verbum", { font: "ANSI Shadow" });

const content = `// src/cli/banner.ts — GENERATED by \`bun run generate:banner\`. Do NOT edit by hand.
// Source: figlet -f "ANSI Shadow" "Verbum"
export const BANNER = \`
${art}
\`;
`;

await Bun.write(outputPath, content);
console.log(`Written: ${outputPath}`);
