// scripts/generate-banner.ts — dev tooling. Generates src/cli/banner.ts.
// Runs figlet twice (two-tone wordmark per D3) and validates parity before writing.
// figlet is a devDependency — NEVER imported by runtime code.

import figlet from "figlet";
import { join } from "path";

const FONT = "ANSI Shadow";
const projectRoot = join(import.meta.dir, "..");
const outputPath = join(projectRoot, "src", "cli", "banner.ts");

function render(text: string): string[] {
  const raw = figlet.textSync(text, { font: FONT });
  return raw.split("\n");
}

const verb = render("Verb");
const um = render("um");

// Parity invariant I8: line counts MUST match. Without this guard the two <span>s
// can't render on the same row in welcome-screen.tsx.
if (verb.length !== um.length) {
  console.error(
    `Banner parity drift: Verb=${verb.length} lines, um=${um.length} lines. Fix the figlet font or the input strings.`
  );
  process.exit(1);
}

// Width parity per row: pad each half to uniform line width per-half so JSX
// concatenation produces a clean column. Per-half only — NOT requiring
// verbWidth === umWidth; they are intentionally different widths (4-2 split).
const verbWidth = Math.max(...verb.map((l) => l.length));
const umWidth = Math.max(...um.map((l) => l.length));
const verbPadded = verb.map((l) => l.padEnd(verbWidth));
const umPadded = um.map((l) => l.padEnd(umWidth));

const totalWidth = verbWidth + umWidth;
const formatArray = (lines: readonly string[]): string =>
  lines.map((l) => `  ${JSON.stringify(l)},`).join("\n");

const content = `// src/cli/banner.ts — GENERATED by \`bun run generate:banner\`. Do NOT edit by hand.
// Source: figlet -f "${FONT}" "Verb" + figlet -f "${FONT}" "um"
//
// Exported as per-line arrays so the welcome screen can render each row as its
// own <text> with two adjacent <span>s. Multi-line strings inside a single
// <span> would force a newline between the dim and accent halves, stacking
// "um" below "Verb" instead of placing them side-by-side.
export const BANNER_DIM_LINES: readonly string[] = [
${formatArray(verbPadded)}
];
export const BANNER_ACCENT_LINES: readonly string[] = [
${formatArray(umPadded)}
];
export const BANNER_WIDTH = ${totalWidth};
`;

await Bun.write(outputPath, content);
console.log(`Written: ${outputPath} (lines=${verb.length}, width=${totalWidth})`);
